# Generated by Django 2.2.3 on 2019-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_manage',
            name='operation_type',
            field=models.IntegerField(help_text='0:养号,1:大V养号,2:大v粉丝发私信,3:同城私信', null=True, verbose_name='操作类型'),
        ),
    ]
