# Generated by Django 2.2.3 on 2019-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论话术',
                'verbose_name_plural': '评论话术',
            },
        ),
        migrations.CreateModel(
            name='Retransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_content', models.CharField(max_length=255, verbose_name='转发描述内容')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '转发话术',
                'verbose_name_plural': '转发话术',
            },
        ),
        migrations.CreateModel(
            name='Talk_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_content', models.CharField(help_text='话术内容默认获取前三个', max_length=255, verbose_name='话术内容')),
                ('status', models.CharField(choices=[('1', '开启'), ('0', '关闭')], default='1', max_length=2, verbose_name='状态')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天话术',
                'verbose_name_plural': '聊天话术',
            },
        ),
        migrations.CreateModel(
            name='Weibo_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_account', models.CharField(max_length=30, unique=True, verbose_name='微博账号')),
                ('weibo_password', models.CharField(max_length=30, verbose_name='微博密码')),
                ('status', models.CharField(choices=[('1', '开启'), ('0', '关闭')], default='1', max_length=2, verbose_name='状态')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微博管理',
                'verbose_name_plural': '微博管理',
            },
        ),
    ]
