# Generated by Django 2.2.3 on 2019-12-31 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20191228_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo_manage',
            name='big_v',
            field=models.CharField(max_length=30, null=True, verbose_name='大vID'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='account',
            field=models.OneToOneField(help_text='请设置关联的帐号信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='users.Account_manage', verbose_name='账号信息'),
        ),
        migrations.AlterField(
            model_name='retransmission',
            name='account',
            field=models.ForeignKey(help_text='请设置关联的帐号信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retransmission', to='users.Account_manage', verbose_name='账号信息'),
        ),
        migrations.AlterField(
            model_name='weibo_manage',
            name='account',
            field=models.ForeignKey(help_text='请设置关联的帐号信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weibo', to='users.Account_manage', verbose_name='账号信息'),
        ),
        migrations.AlterField(
            model_name='weibo_manage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='请选择关联的帐号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weibo', to=settings.AUTH_USER_MODEL, verbose_name='用户信息'),
        ),
    ]
