# Generated by Django 2.2.3 on 2019-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='账号id')),
                ('function_type', models.IntegerField(verbose_name='功能类型')),
                ('total_number', models.IntegerField(default=1, verbose_name='使用次数')),
                ('write_time', models.IntegerField(default=1577462400, verbose_name='数据写入日期')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
            },
        ),
    ]
