# Generated by Django 2.2.3 on 2019-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_statistics',
            name='write_time',
            field=models.IntegerField(default=1577721600, verbose_name='数据写入日期'),
        ),
    ]
