# Generated by Django 2.2.3 on 2019-12-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='标题')),
                ('key_word', models.CharField(max_length=30, null=True, verbose_name='操作key')),
                ('value', models.CharField(max_length=30, null=True, verbose_name='设置参数')),
                ('status', models.CharField(choices=[('1', '开启'), ('0', '关闭')], default='1', max_length=2, verbose_name='状态')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '后台系统设置',
                'verbose_name_plural': '后台系统设置',
            },
        ),
        migrations.CreateModel(
            name='Douyin_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='标题')),
                ('key', models.CharField(max_length=30, null=True, verbose_name='操作key')),
                ('default_value', models.CharField(default='0', max_length=30, verbose_name='设置默认值')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '全局抖音APP设置',
                'verbose_name_plural': '全局抖音APP设置',
            },
        ),
        migrations.CreateModel(
            name='User_link_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_value', models.IntegerField(help_text='时间的单位为：毫秒', null=True, verbose_name='数值')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('set_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_user', to='system_setup.Douyin_setup', verbose_name='设置信息')),
            ],
            options={
                'verbose_name': '个人抖音app设置',
                'verbose_name_plural': '个人抖音app设置',
            },
        ),
    ]
