# Generated by Django 2.2.3 on 2019-12-31 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_setup', '0002_auto_20191228_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_watch', models.IntegerField(default=0, help_text='单位：次数', verbose_name='每日观看上限')),
                ('watch_duration_min', models.IntegerField(default=0, help_text='单位：秒', verbose_name='观看时长最小值')),
                ('watch_duration_max', models.IntegerField(default=0, verbose_name='观看时长最大值')),
                ('watch_times', models.IntegerField(default=0, help_text='观看多少个视频后，随机暂停', verbose_name='观看视频数')),
                ('pause_times_min', models.IntegerField(default=0, help_text='单位：秒', verbose_name='暂停时间最小值')),
                ('pause_times_max', models.IntegerField(default=0, verbose_name='暂停时间最大值')),
                ('nice_probability', models.FloatField(default=0, help_text='请填写0到1之间的小数', verbose_name='点赞概率')),
                ('comment_probability', models.FloatField(default=0, verbose_name='评论概率')),
                ('comment_nice_probability', models.FloatField(default=0, help_text='请填写0到1之间的小数', verbose_name='在评论区点赞的概率')),
                ('comment_nice_min_times', models.IntegerField(default=0, verbose_name='评论区点赞的最小次数')),
                ('comment_nice_mix_times', models.IntegerField(default=0, verbose_name='评论区点赞的最大次数')),
                ('forward_probability', models.FloatField(default=0, help_text='请填写0到1之间的小数', verbose_name='转发概率')),
                ('follw_author_probability', models.FloatField(default=0, help_text='请填写0到1之间的小数', verbose_name='关注作者的概率')),
                ('follw_author_pause_time_min', models.IntegerField(default=0, help_text='单位：秒', verbose_name='关注作者前的暂停时间最小值')),
                ('follw_author_pause_time_max', models.IntegerField(default=0, verbose_name='关注作者前的暂停时间最大值')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='culture_account', to=settings.AUTH_USER_MODEL, verbose_name='养号设置')),
            ],
            options={
                'verbose_name': '养号规则设置',
                'verbose_name_plural': '养号规则设置',
            },
        ),
    ]
