# Generated by Django 2.2.3 on 2019-12-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setup', '0003_culture_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture_account',
            old_name='follw_author_pause_time_max',
            new_name='follow_author_pause_time_max',
        ),
        migrations.RenameField(
            model_name='culture_account',
            old_name='follw_author_pause_time_min',
            new_name='follow_author_pause_time_min',
        ),
        migrations.RenameField(
            model_name='culture_account',
            old_name='follw_author_probability',
            new_name='follow_author_probability',
        ),
    ]
