# Generated by Django 2.2.3 on 2019-12-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setup', '0004_auto_20191231_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture_account',
            old_name='comment_nice_mix_times',
            new_name='comment_nice_max_times',
        ),
    ]
