# Generated by Django 2.2.3 on 2020-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setup', '0005_auto_20191231_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture_account',
            name='comment_nice_max_times',
            field=models.IntegerField(default=3, verbose_name='评论区点赞的最大次数'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='comment_nice_min_times',
            field=models.IntegerField(default=1, verbose_name='评论区点赞的最小次数'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='comment_nice_probability',
            field=models.FloatField(default=0.2, help_text='请填写0到1之间的小数', verbose_name='在评论区点赞的概率'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='comment_probability',
            field=models.FloatField(default=0.2, verbose_name='评论概率'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='follow_author_pause_time_max',
            field=models.IntegerField(default=4000, help_text='单位：毫秒', verbose_name='关注作者前的暂停时间最大值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='follow_author_pause_time_min',
            field=models.IntegerField(default=2000, help_text='单位：毫秒', verbose_name='关注作者前的暂停时间最小值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='follow_author_probability',
            field=models.FloatField(default=0.2, help_text='请填写0到1之间的小数', verbose_name='关注作者的概率'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='forward_probability',
            field=models.FloatField(default=0.2, help_text='请填写0到1之间的小数', verbose_name='转发概率'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='limit_watch',
            field=models.IntegerField(default=50, help_text='单位：次数', verbose_name='每日观看上限'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='nice_probability',
            field=models.FloatField(default=0.2, help_text='请填写0到1之间的小数', verbose_name='点赞概率'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='pause_times_max',
            field=models.IntegerField(default=6000, help_text='单位：毫秒', verbose_name='暂停时间最大值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='pause_times_min',
            field=models.IntegerField(default=3000, help_text='单位：毫秒', verbose_name='暂停时间最小值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='watch_duration_max',
            field=models.IntegerField(default=7000, help_text='单位：毫秒', verbose_name='观看时长最大值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='watch_duration_min',
            field=models.IntegerField(default=3000, help_text='单位：毫秒', verbose_name='观看时长最小值'),
        ),
        migrations.AlterField(
            model_name='culture_account',
            name='watch_times',
            field=models.IntegerField(default=3, help_text='观看多少个视频后，随机暂停', verbose_name='观看视频数'),
        ),
    ]
