# Generated by Django 2.2.3 on 2020-01-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setup', '0006_auto_20200101_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture_account',
            old_name='pause_times_max',
            new_name='pause_time_max',
        ),
        migrations.RenameField(
            model_name='culture_account',
            old_name='pause_times_min',
            new_name='pause_time_min',
        ),
    ]
