# Generated by Django 2.2.3 on 2020-01-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appdownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='app标题')),
                ('remarks', models.CharField(blank=True, max_length=120, null=True, verbose_name='版本备注')),
                ('app_file', models.FileField(blank=True, upload_to='app', verbose_name='app下载地址')),
                ('download', models.CharField(choices=[('1', '开启下载'), ('0', '关闭下载')], max_length=2, verbose_name='是否开启下载')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'app下载',
                'verbose_name_plural': 'app下载',
            },
        ),
        migrations.CreateModel(
            name='Control_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('download', models.CharField(choices=[('1', '开启下载'), ('0', '关闭下载')], max_length=5, verbose_name='是否开启全局下载')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '下载控制',
                'verbose_name_plural': '下载控制',
            },
        ),
    ]
